<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Revenue Report - {{ $year }}</title>

    <style>
        @page {
            margin: 20px;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        .header-table {
            width: auto;
            margin: 0 auto 10px auto;
            border-collapse: collapse;
            text-align: center;
            margin-bottom: 50px;
        }

        .header-table td {
            border: none;
            vertical-align: middle;
            padding: 2px 4px;
        }

        .header-logo {
            width: 90px;
        }

        h3 {
            margin: 2px 0;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            page-break-inside: avoid;
        }

        th,
        td {
            border: 0.7px solid #000;
            padding: 7px;
            text-align: center;
        }

        th {
            background-color: #91f4b0;
        }

        .total-row {
            font-weight: bold;
            background-color: #ffa9a9;
        }

        .page-break {
            page-break-before: always;
        }

        .report-title {
            text-align: left;
            font-weight: normal;
            margin-top: 10px;
        }
    </style>
</head>

<body>

    <table class="header-table">
        <tr>
            <td class="header-logo" style="text-align: right;">
                <img src="{{ public_path('drcare_logo.png') }}" width="70">
            </td>

            <td style="text-align: center; padding: 0 10px;">
                <h3 style="margin: 0; font-weight: normal;">Region V Albay</h3>
                <h3 style="margin: 0; font-weight: normal;">Municipality of Guinobatan</h3>
                <h3 style="margin: 0; font-weight: 600;">Dr. Care Guinobatan Animal Bite Center</h3>
                <h3 style="margin: 4px 0; font-weight: normal;">Revenue & Expense Report - {{ $year }}</h3>
            </td>

            <td class="header-logo" style="text-align: left;">
                <img src="{{ public_path('images/rabies-free.jpg') }}" width="70">
            </td>
        </tr>
    </table>

    <table style="width: 100%; font-weight: normal; border: none;">
        <tr>
            <td style="text-align: left; border:none;">Financial Summary</td>
            <td style="text-align: right; border:none;">Year: {{ $year }}</td>
        </tr>
    </table>

    <table class="content">
        <thead>
            <tr>
                <th>Month</th>
                <th>Total Revenue (&#8369;)</th>
                <th>Total Expenses (&#8369;)</th>
                <th>Income (&#8369;)</th>
                <th>Loss (&#8369;)</th>
            </tr>
        </thead>
        <tbody>
            @php
            $totalRevenue = $datas->sum('total_revenue');
            $totalExpenses = $datas->sum('total_expenses');
            $totalIncome = $datas->sum('income');
            $totalLoss = $datas->sum('loss');
            @endphp

            @foreach($datas as $data)
            <tr>
                <td>{{ $data->month }}</td>
                <td>{{ number_format($data->total_revenue, 2) }}</td>
                <td>{{ number_format($data->total_expenses, 2) }}</td>
                <td>{{ number_format($data->income, 2) }}</td>
                <td>{{ number_format($data->loss, 2) }}</td>
            </tr>
            @endforeach

            <tr style="background-color: #ffffff; height: 240px;">
                <td colspan="5"></td>
            </tr>

            <tr class="total-row">
                <td>Total</td>
                <td>&#8369;{{ number_format($totalRevenue, 2) }}</td>
                <td>&#8369;{{ number_format($totalExpenses, 2) }}</td>
                <td>&#8369;{{ number_format($totalIncome, 2) }}</td>
                <td>&#8369;{{ number_format($totalLoss, 2) }}</td>
            </tr>

          
            <tr style="background-color: #ffffff; height: 240px; border:none;">
                <td colspan="5" style="border:none;"></td>
            </tr>
            <tr style="background-color: #ffffff; height: 240px; border:none;">
                <td colspan="5" style="border:none;"></td>
            </tr>
            <tr>
                <td colspan="5" style="text-align:right; border:none; font-size:10px; font-style:italic;">
                    Generated by iBiteCare+ System
                    on {{ \Carbon\Carbon::now()->format('F d, Y h:i A') }}
                </td>
            </tr>
        </tbody>
    </table>

</body>

</html>